### PR TITLE
bump to 2.2.2

### PR DESCRIPTION
**Pull request by robbkidd**
- [x] update changelog
- [x] bump version in build script
- [x] bump version in common package
---
- ~update CI to run `build.sh` on tagging events?~ That's over on #49.
- [ ] rebase this branch to update to new build'n'publish automation

### CODE REVIEW

**Comment by robbkidd** [comment]
I notice that neither CircleCI nor GitHub Actions will run the `build.sh` script to publish these to S3. Has that been run manually in the past? Is that something to add to CI on tagging events?

**Review by MikeGoldsmith — APPROVED** [review]
Would be nice for CI to publish to S3 based on release tag - this is general pattern we've used for many other projects 👍🏻 

This could be done separately from this change though.

**Review by robbkidd — COMMENTED** [review]
I'd like to wait to merge this PR until it can be rebased to a main that includes #49 to ease release efforts.

**Comment by robbkidd** [comment]
Rebased and merging. :shipit: 🚀 🍰

**Pull request merged**
